[project]
name = "cs_geodata"
version = "0.2.0"
description = "Library to convert, save and load geodata from zarr and parquet formats."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
    "dask>=2025.12.0",
    "requests>=2.32.5",
    "rioxarray>=0.20.0",
    "tqdm>=4.67.1",
    "xarray>=2025.12.0",
    "zarr>=3.1.5",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=1.3.0",
    "pytest-asyncio>=0.25.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.11",
]
docs = [
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "sphinx-autodoc-typehints>=2.5.0",
    "autodocsumm>=0.2.14",
    "sphinx-conestack-theme>=1.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ["--import-mode=importlib"]
